language: node_js
node_js:
  - "4.1"
before_install:
  - 'npm install --global jspm@beta'
  - 'jspm --version'
  - 'jspm config registries.github.auth "$JSPM_GITHUB_AUTH_TOKEN"'
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
